// Drive the actual UI through visitor controls. No providers, downloads or app server.
import assert from 'node:assert/strict'
import { mkdir, readFile } from 'node:fs/promises'
import { resolve, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { chromium } from 'playwright-core'
const file = fileURLToPath(new URL('./index.html', import.meta.url))
const { version } = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'))
const featureGroups = JSON.parse(await readFile(new URL('./features.json', import.meta.url), 'utf8'))
const featureCount = featureGroups.reduce((count, group) => count + group.items.length, 0)
const evidence = process.argv[2] && resolve(process.argv[2])
if (evidence) await mkdir(evidence, { recursive: true })
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const targets = [{ name: 'file', url: pathToFileURL(file).href, offline: true }]
if (process.env.LANDING_URL) targets.push({ name: 'http', url: process.env.LANDING_URL, offline: false })
try {
  for (const target of targets) for (const width of [360, 390, 768, 1280, 1440]) {
    const context = await browser.newContext({ viewport: { width, height: 1000 }, offline: target.offline, reducedMotion: 'reduce' })
    const page = await context.newPage(); page.setDefaultTimeout(10000)
    const errors = [], requests = [], demoRequests = []
    page.on('pageerror', e => errors.push(e.message))
    page.on('request', r => {
      if (!/^https?:/.test(r.url())) return
      requests.push(r.url())
      if (r.frame().parentFrame()) demoRequests.push(r.url())
    })
    await page.goto(target.url)
    const app = page.frameLocator('#demo-frame')
    const button = name => app.getByRole('button', { name, exact: true })
    const section = name => app.getByRole('tab', { name, exact: true }).click()
    const shot = async name => { if (evidence) await page.locator('#demo-container').screenshot({ path: join(evidence, `${target.name}-${width}-${name}.png`) }) }
    const noOverflow = async () => {
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'page overflow')
      assert.equal(await app.locator('html').evaluate(el => el.scrollWidth > innerWidth), false, 'demo overflow')
    }
    assert.equal(await page.locator('h1').count(), 1)
    assert.ok((await page.locator('.release-chip').innerText()).includes(`v${version}`))
    assert.ok(await page.locator('.hero-copy > p').first().evaluate(el => parseFloat(getComputedStyle(el).fontSize) >= 19))
    await page.getByRole('link', { name: 'Try the flow' }).click()
    await button('Allow').waitFor(); await noOverflow(); await shot('approval')
    assert.ok(await app.locator('.bubble.user').first().evaluate(el => parseFloat(getComputedStyle(el).fontSize) >= 16))
    await button('Allow').click()
    const sample = app.frameLocator('.preview-pane iframe')
    await sample.locator('[data-plant="basil"]').getByRole('button', { name: 'Mark watered' }).click()
    assert.equal(await sample.locator('#progress-label').innerText(), '1 of 3 watered')
    await page.getByText('You tried the change.', { exact: true }).waitFor()
    await sample.getByRole('button', { name: 'Needs water' }).click()
    assert.equal(await sample.locator('[data-plant="basil"]').isVisible(), false)
    await sample.getByRole('button', { name: 'All plants' }).click()
    assert.equal(await sample.locator('[data-plant="basil"]').isVisible(), true)
    assert.equal(await sample.locator('html').evaluate(el => el.scrollWidth > innerWidth), false, 'sample app overflow')
    assert.ok(await sample.locator('.plant p').first().evaluate(el => parseFloat(getComputedStyle(el).fontSize) >= 14), 'sample app text too small')
    await noOverflow(); await shot('preview'); await button('Close preview').click()
    await section('Files'); await button('notes.md').click(); await button('Source').click()
    const contents = app.getByLabel('File contents', { exact: true })
    const original = await contents.inputValue()
    const note = '# Readable by design\nMake the text bigger. <img src=x onerror=alert(1)>'
    await contents.fill(note)
    async function runWorkflow() {
      await section('Workflows')
      await app.getByRole('button', { name: /Review before sharing/ }).click()
      await button('Save and run').click()
      await app.getByText('Sample review (fixed, no model call):', { exact: false }).waitFor()
    }
    await runWorkflow()
    assert.ok((await app.locator('.transcript').innerText()).includes(original.trim()), 'workflow reads saved notes, not draft')
    assert.equal((await app.locator('.transcript').innerText()).includes(note), false)
    await section('Files'); await contents.waitFor()
    assert.equal(await contents.inputValue(), note, 'draft survives navigation')
    await button('Save').press('Enter'); await page.getByText('Your next step is saved.', { exact: true }).waitFor(); await shot('files')
    await runWorkflow()
    assert.ok((await app.locator('.transcript').innerText()).includes(note))
    assert.equal(await app.locator('.transcript img').count(), 0, 'sample input stays text')
    await shot('workflow-result')
    await button('Agent settings').click(); await app.getByRole('radio', { name: 'Codex', exact: true }).click(); await button('Switch').click()
    await app.getByText(/Handed over from Claude Code to Codex/).waitFor()
    assert.match(await button('Agent settings').innerText(), /Codex/)
    assert.ok((await app.locator('.transcript').innerText()).includes(note), 'handoff preserves conversation'); await shot('handoff')
    await page.getByRole('button', { name: 'Reset demo', exact: true }).click()
    await button('Deny').click(); await app.getByText(/Startup denied/).waitFor()
    assert.equal(await app.locator('.preview-pane').count(), 0)
    await app.getByLabel('Message', { exact: true }).fill('start the app'); await button('Send').click(); await button('Allow').waitFor()
    await section('Files'); await button('notes.md').click(); await button('Source').click()
    assert.equal(await contents.inputValue(), original, 'reset clears saved notes and drafts')
    await page.locator('[data-demo-action="recovery"]').click(); await button('Open a project').click()
    await app.getByLabel('Recovery agent', { exact: true }).selectOption('codex'); await shot('recovery')
    await button('Resume and show me the app').click(); await button('Allow').waitFor()
    assert.match(await app.locator('.approval').innerText(), /Codex wants to use Start a process/)
    await button('Deny').click()
    await page.getByRole('button', { name: 'Expand ↗', exact: true }).click()
    assert.equal(await page.locator('#expand-demo').getAttribute('aria-expanded'), 'true')
    await app.getByLabel('Message', { exact: true }).press('Escape')
    await page.waitForFunction(() => document.getElementById('expand-demo').getAttribute('aria-expanded') === 'false')
    for (const name of ['Saved workflows', 'Files & documents', 'Recent work', 'Inspected preview']) {
      await page.getByRole('group', { name: 'Product screenshots' }).getByRole('button', { name, exact: true }).click(); await page.locator('#product-shot').scrollIntoViewIfNeeded()
      await page.waitForFunction(() => { const img = document.getElementById('product-shot'); return img.complete && img.naturalWidth > 0 })
    }
    await page.getByRole('button', { name: 'Enlarge product screenshot' }).click(); assert.equal(await page.getByRole('dialog').isVisible(), true)
    await page.keyboard.press('Escape'); assert.equal(await page.getByRole('dialog').isVisible(), false)
    await page.locator('#features').scrollIntoViewIfNeeded()
    const directory = page.locator('#features details')
    await directory.locator('summary').click()
    assert.equal(await directory.locator('.feature-group').count(), featureGroups.length)
    assert.equal(await directory.locator('li').count(), featureCount)
    await noOverflow()
    await directory.locator('summary').click()
    await page.getByText('What should I expect from the prerelease?', { exact: true }).click(); assert.equal(await page.locator('details[open]').count(), 1)
    assert.equal(await page.locator('#download').getAttribute('href'), `https://github.com/Holodeck23/agent-cockpit/releases/download/v${version}/Cockpit-${version}-arm64.dmg`)
    await noOverflow(); assert.deepEqual(errors, [])
    assert.deepEqual(demoRequests, [], 'no network calls from demo')
    if (target.offline) assert.deepEqual(requests, [], 'offline page makes no network calls')
    if (evidence) await page.screenshot({ path: join(evidence, `${target.name}-${width}-page.png`), fullPage: true })
    console.log(`PASS ${target.name} ${width}px: approval/denial/retry, garden preview, draft/save/workflow, handoff, reset, recovery, expand/Escape, gallery/FAQ, readable type, zero API calls`)
    await context.close()
  }
  const fallback = await browser.newContext({ javaScriptEnabled: false, offline: true, viewport: { width: 390, height: 900 } })
  const page = await fallback.newPage(); await page.goto(pathToFileURL(file).href)
  assert.equal(await page.locator('.no-js').isVisible(), true); assert.equal(await page.locator('.demo-container').isVisible(), false); assert.equal(await page.locator('#download').isVisible(), true)
  console.log('PASS JavaScript disabled: readable page, screenshots and release link')
  await fallback.close()
} finally { await browser.close() }
